---
- name: Install VirtualControl4
  hosts: all
  gather_facts: yes
  become: yes
  vars:
    vc4_action: install
  tasks:
    - name: Setup passwordless sudo
      lineinfile:
        path: /etc/sudoers
        regexp: "^%wheel *"
        line: "%wheel ALL=(ALL) NOPASSWD:ALL"
        state: present
        mode: 0440
        owner: root
        group: root
        create: yes
        validate: "/usr/sbin/visudo -cf %s"

    - name: Run VirtualControl Role
      include_role:
        name: virtualcontrol

    - name: Run Additional VirtualControl Configuration
      include_role:
        name: virtualcontrol
      vars:
        vc4_action: config
